spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/propostas}
    username: ${DB_USER:keycloak}
    password: ${DB_PW:password}
    initialization-mode: always
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

servicos:
  analise: ${URL_ANALISE:http://localhost:9999/api}
  contas: ${URL_CONTAS:http://localhost:8888/api}