spring:
  application:
    name: proposta
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/propostas}
    username: ${DB_USER:keycloak}
    password: ${DB_PW:password}
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/nosso-cartao}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/nosso-cartao/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus

opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    service-name: ${spring.application.name}
    http-sender:
      url: ${JAEGER_ENDPOINT:http://localhost:14268/api/traces}
    probabilistic-sampler:
      sampling-rate: ${JAEGER_SAMPLER:1}

servicos:
  analise: ${URL_ANALISE:http://localhost:9999/api}
  contas: ${URL_CONTAS:http://localhost:8888/api}